apiVersion: operator.tkestack.io/v1alpha1
kind: Fabric
metadata:
  name: fabric-sample
spec:
  # Add fields here
  brokerConfig:
    # ipsecSubmFile:
    globalnetEnable: false
    # globalnetCIDRRange:
    # globalCIDRConfigMap:
    # defaultGlobalnetClusterSize:
    serviceDiscoveryEnabled: true
    componentArr:
    - service-discovery
    - connectivity
    # defaultCustomDomains:
  joinConfig:
    clusterID: cls-mdl3wn46
  # cloudPrepareConfig:
